import Container from "../components/container";
import MoreStories from "../components/more-stories";
import HeroPost from "../components/hero-post";
import Intro from "../components/intro";
import Layout from "../components/layout";
import { getAllPosts } from "../lib/api";
import Head from "next/head";
import { CMS_NAME } from "../lib/constants";
import Post from "../types/post";

type Props = {
    allPosts: Post[];
};

const Index = ({ allPosts }: Props) => {
    const heroPost = allPosts[0];
    const morePosts = allPosts.slice(1);

    return (
        <>
            <Head>
                <title>richiecarey.com</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <header>
                <div className="site">
                    <h1>Richie Carey</h1>
                    <p>Web Developer</p>
                </div>
                <div className="contact">
                    <p>GitHub</p>
                </div>
            </header>

            {
                <Layout>
                    <Head>
                        <title>Next.js Blog Example with {CMS_NAME}</title>
                    </Head>
                    <Container>
                        <Intro />
                        {/* {heroPost && (
                            <HeroPost
                                title={heroPost.title}
                                coverImage={heroPost.coverImage}
                                date={heroPost.date}
                                slug={heroPost.slug}
                                excerpt={heroPost.excerpt}
                            />
                        )} */}
                        {morePosts.length > 0 && (
                            <MoreStories posts={morePosts} />
                        )}
                    </Container>
                </Layout>
            }
        </>
    );
};

export default Index;

export const getStaticProps = async () => {
    const allPosts = getAllPosts([
        "title",
        "date",
        "slug",
        "author",
        "coverImage",
        "excerpt",
    ]);

    return {
        props: { allPosts },
    };
};
